#!/bin/bash
#
# colors: variables for color text in scripts
# Original content from ArchLinux Wiki:
# https://wiki.archlinux.org/index.php/Color_Bash_Prompt
#
#    Copyright (c)  2015  Arch Linux Project
#    Permission is granted to copy, distribute and/or modify this document
#    under the terms of the GNU Free Documentation License, Version 1.3
#    or any later version published by the Free Software Foundation;
#    with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
#    A copy of the license is included in the section entitled "GNU
#    Free Documentation License".
#

# Reset
esc='\e[0m'       # Text Reset

# Regular Colors
black='\e[0;30m'        # Black
red='\e[0;31m'          # Red
green='\e[0;32m'        # Green
yellow='\e[0;33m'       # Yellow
blue='\e[0;34m'         # Blue
purple='\e[0;35m'       # Purple
cyan='\e[0;36m'         # Cyan
white='\e[0;37m'        # White

# Bold
bblack='\e[1;30m'       # Black
bred='\e[1;31m'         # Red
bgreen='\e[1;32m'       # Green
byellow='\e[1;33m'      # Yellow
bblue='\e[1;34m'        # Blue
bpurple='\e[1;35m'      # Purple
bcyan='\e[1;36m'        # Cyan
bwhite='\e[1;37m'       # White

# Underline
ublack='\e[4;30m'       # Black
ured='\e[4;31m'         # Red
ugreen='\e[4;32m'       # Green
uyellow='\e[4;33m'      # Yellow
ublue='\e[4;34m'        # Blue
upurple='\e[4;35m'      # Purple
ucyan='\e[4;36m'        # Cyan
uwhite='\e[4;37m'       # White

# Background
On_Black='\e[40m'       # Black
On_Red='\e[41m'         # Red
On_Green='\e[42m'       # Green
On_Yellow='\e[43m'      # Yellow
On_Blue='\e[44m'        # Blue
On_Purple='\e[45m'      # Purple
On_Cyan='\e[46m'        # Cyan
On_White='\e[47m'       # White

# High Intensity
iblack='\e[0;90m'       # Black
ired='\e[0;91m'         # Red
igreen='\e[0;92m'       # Green
iyellow='\e[0;93m'      # Yellow
iblue='\e[0;94m'        # Blue
ipurple='\e[0;95m'      # Purple
icyan='\e[0;96m'        # Cyan
iwhite='\e[0;97m'       # White

# Bold High Intensity
biblack='\e[1;90m'      # Black
bired='\e[1;91m'        # Red
bigreen='\e[1;92m'      # Green
biyellow='\e[1;93m'     # Yellow
biblue='\e[1;94m'       # Blue
bipurple='\e[1;95m'     # Purple
bicyan='\e[1;96m'       # Cyan
biwhite='\e[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\e[0;100m'   # Black
On_IRed='\e[0;101m'     # Red
On_IGreen='\e[0;102m'   # Green
On_IYellow='\e[0;103m'  # Yellow
On_IBlue='\e[0;104m'    # Blue
On_IPurple='\e[0;105m'  # Purple
On_ICyan='\e[0;106m'    # Cyan
On_IWhite='\e[0;107m'   # White

line="================================================================================"
